# Generated by Django 4.1.3 on 2022-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timg', models.ImageField(upload_to='teamimage')),
                ('tname', models.CharField(max_length=200)),
                ('tdesc', models.TextField()),
            ],
        ),
    ]
