# Generated by Django 4.1.3 on 2022-11-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_team_meetteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meetteam',
            new_name='team',
        ),
    ]
