# Generated by Django 4.1.3 on 2023-06-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='username',
            new_name='name',
        ),
    ]
