# Generated by Django 4.2.4 on 2024-04-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_iseller',
            new_name='is_seller',
        ),
    ]
