# Generated by Django 4.2.4 on 2024-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_rename_is_iseller_user_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mileage', models.FloatField()),
                ('petrol', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('registration_year', models.IntegerField()),
                ('registration_number', models.CharField(max_length=20)),
                ('engine_capacity', models.FloatField()),
                ('insurance', models.BooleanField(default=False)),
                ('spare_key', models.BooleanField(default=False)),
                ('transmission', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
            ],
        ),
    ]
