# Generated by Django 4.2.4 on 2024-04-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_remove_cars_petrol_cars_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='registration_year',
            field=models.DateField(),
        ),
    ]
