# Generated by Django 4.2.4 on 2024-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_alter_cars_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='img',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
    ]
