# Generated by Django 4.2.4 on 2024-04-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0014_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='seller',
            new_name='user',
        ),
    ]
