# Generated by Django 4.2.4 on 2024-04-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0018_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralreward',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralReward',
        ),
    ]
