# Generated by Django 4.2.4 on 2024-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0020_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward',
            field=models.IntegerField(null=True),
        ),
    ]
